/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/pulse-verified-gc/generational/../fstar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -bundle GC.Gen.Impl+GC.Gen.Impl.MinorHeap+GC.Gen.Impl.Cheney+GC.Gen.Impl.UpdatePtrs+GC.Impl+GC.Impl.Allocator+GC.Impl.MarkBounded=GC.Gen.Impl.*,GC.Impl.*[rename=GC_Gen_Impl] -bundle FStar.Pervasives.Native -bundle GC.Spec.ZeroAddr=GC.Spec.ZeroAddr -bundle GC.Gen.Base,GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Gen.Impl -no-prefix GC.Gen.Impl.MinorHeap -no-prefix GC.Gen.Impl.Cheney -no-prefix GC.Gen.Impl.Promote -no-prefix GC.Gen.Impl.UpdatePtrs -no-prefix GC.Gen.Base -no-prefix GC.Impl -no-prefix GC.Impl.Fields -no-prefix GC.Impl.MarkBounded -no-prefix GC.Impl.Coalesce -no-prefix GC.Impl.FusedSweepCoalesce -no-prefix GC.Impl.Allocator -no-prefix GC.Impl.ArrayWord -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -no-prefix GC.Spec.ZeroAddr -no-prefix GC.Spec.Base -no-prefix GC.Spec.Heap -no-prefix GC.Spec.Object -no-prefix GC.Lib.Header -no-prefix GC.Lib.Address -warn-error -2-9-15 _output/GC_Gen_Impl.krml _output/GC_Gen_Impl_MinorHeap.krml _output/GC_Gen_Impl_Cheney.krml _output/GC_Gen_Impl_Promote.krml _output/GC_Gen_Impl_UpdatePtrs.krml _output/GC_Gen_Base.krml _output/GC_Impl.krml _output/GC_Impl_Fields.krml _output/GC_Impl_MarkBounded.krml _output/GC_Impl_Coalesce.krml _output/GC_Impl_FusedSweepCoalesce.krml _output/GC_Impl_Allocator.krml _output/GC_Impl_ArrayWord.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/GC_Spec_ZeroAddr.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml _output/FStar_Pervasives_Native.krml
  F* version: <unknown>
  KaRaMeL version: 2309d841d896e5f2b0fec73884657eefea5fad6e
 */

#include "internal/GC_Gen_Impl.h"

#include "internal/GC_Gen_Base_GC_Spec_GC_Lib_Header_GC_Lib_Address.h"

extern uint64_t read_u64_le(uint8_t *arr, size_t offset);

extern void write_u64_le(uint8_t *arr, size_t offset, uint64_t v);

uint64_t zero_addr1;

static uint64_t read_word(heap_t h, uint64_t addr)
{
  size_t base = (size_t)addr;
  return read_u64_le(h.data, base);
}

static void write_word(heap_t h, uint64_t addr, uint64_t v)
{
  size_t base = (size_t)addr;
  write_u64_le(h.data, base, v);
}

static uint64_t hd_address(uint64_t f_addr)
{
  return f_addr - 8ULL;
}

static uint64_t f_address(uint64_t h_addr)
{
  return h_addr + 8ULL;
}

static bool is_empty(gray_stack_rec st)
{
  size_t top_val = *st.top;
  return top_val == st.cap;
}

static bool is_full(gray_stack_rec st)
{
  size_t top_val = *st.top;
  return top_val == (size_t)0U;
}

static void push(gray_stack_rec st, uint64_t addr)
{
  size_t top_val = *st.top;
  size_t new_top = top_val - (size_t)1U;
  st.storage[new_top] = addr;
  *st.top = new_top;
}

static uint64_t pop(gray_stack_rec st)
{
  size_t top_val = *st.top;
  uint64_t v_raw = st.storage[top_val];
  size_t new_top = top_val + (size_t)1U;
  *st.top = new_top;
  return v_raw;
}

static color_sem white = White;

static color_sem gray = Gray;

static color_sem blue = Blue;

static color_sem black = Black;

static uint64_t infix_tag = 249ULL;

static uint64_t no_scan_tag = 251ULL;

static uint64_t getWosize0(uint64_t hdr)
{
  return hdr >> 10U;
}

static uint64_t getTag(uint64_t hdr)
{
  return hdr & 0xFFULL;
}

static uint64_t makeHeader(uint64_t wz, color_sem c, uint64_t t)
{
  uint64_t c_num;
  switch (c)
  {
    case White:
      {
        c_num = 0ULL;
        break;
      }
    case Gray:
      {
        c_num = 1ULL;
        break;
      }
    case Blue:
      {
        c_num = 2ULL;
        break;
      }
    case Black:
      {
        c_num = 3ULL;
        break;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
  uint64_t wz_shifted = wz << 10U;
  uint64_t c_shifted = c_num << 8U;
  return wz_shifted | c_shifted | t;
}

static void
copy_fields_loop(
  minor_heap_t minor,
  heap_t major,
  uint64_t src_obj,
  uint64_t dst_obj,
  uint64_t wosize
)
{
  uint64_t i = 0ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 < wosize;
  while (cond)
  {
    uint64_t iv = i;
    uint64_t src_off = iv * 8ULL;
    uint64_t src_addr = src_obj + src_off;
    uint64_t field_val = minor_read(minor, src_addr);
    uint64_t dst_off = iv * 8ULL;
    uint64_t dst_addr = dst_obj + dst_off;
    write_word(major, dst_addr, field_val);
    i = iv + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 < wosize;
  }
}

static uint64_t field_address_pure(uint64_t h_addr, uint64_t i)
{
  uint64_t offset = i * 8ULL;
  return h_addr + offset;
}

static uint64_t read_field(heap_t heap, uint64_t h_addr, uint64_t i)
{
  uint64_t addr = field_address_pure(h_addr, i);
  uint64_t addr_hp = addr;
  return read_word(heap, addr_hp);
}

static bool is_pointer(uint64_t v)
{
  uint64_t lo = zero_addr1 + 8ULL;
  if (v < lo)
    return false;
  else if (v >= heap_size_u640)
    return false;
  else
  {
    uint64_t rem = v % 8ULL;
    return rem == 0ULL;
  }
}

static void flush_blue_write_header(heap_t heap, uint64_t fb, uint64_t rw)
{
  uint64_t hd = fb - 8ULL;
  uint64_t wz = rw - 1ULL;
  uint64_t hdr = makeHeader(wz, blue, 0ULL);
  write_word(heap, hd, hdr);
}

static void flush_blue_write_link(heap_t heap, uint64_t fb, uint64_t fp)
{
  write_word(heap, fb, fp);
}

static void zero_fields_loop(heap_t heap, uint64_t start_addr, uint64_t n)
{
  uint64_t idx = 0ULL;
  uint64_t addr = start_addr;
  uint64_t __anf0 = idx;
  bool cond = __anf0 < n;
  while (cond)
  {
    uint64_t cur_a = addr;
    uint64_t cur_i = idx;
    write_word(heap, cur_a, 0ULL);
    uint64_t next_a = cur_a + 8ULL;
    uint64_t next_i = cur_i + 1ULL;
    addr = next_a;
    idx = next_i;
    uint64_t __anf0 = idx;
    cond = __anf0 < n;
  }
}

static K___uint64_t_uint64_t
flush_blue_impl(heap_t heap, uint64_t fb, uint64_t rw, uint64_t fp)
{
  if (rw == 0ULL)
    return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fp });
  else
  {
    flush_blue_write_header(heap, fb, rw);
    uint64_t wz = rw - 1ULL;
    if (wz > 0ULL)
    {
      flush_blue_write_link(heap, fb, fp);
      if (wz > 1ULL)
      {
        uint64_t zero_start = fb + 8ULL;
        uint64_t n_zero = wz - 1ULL;
        zero_fields_loop(heap, zero_start, n_zero);
        return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fb });
      }
      else
        return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fb });
    }
    else
      return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fp });
  }
}

static uint64_t fst__uint64_t_uint64_t(K___uint64_t_uint64_t x)
{
  return x.fst;
}

static uint64_t snd__uint64_t_uint64_t(K___uint64_t_uint64_t x)
{
  return x.snd;
}

static uint64_t fused_sweep_coalesce(heap_t heap)
{
  uint64_t current = zero_addr1;
  uint64_t fb_ref = 0ULL;
  uint64_t rw_ref = 0ULL;
  uint64_t fp_ref = 0ULL;
  uint64_t __anf0 = current;
  bool cond = __anf0 + 8ULL < heap_size_u640;
  while (cond)
  {
    uint64_t cur = current;
    uint64_t cur_fb = fb_ref;
    uint64_t cur_rw = rw_ref;
    uint64_t cur_fv = fp_ref;
    uint64_t hdr = read_word(heap, cur);
    uint64_t wz = getWosize0(hdr);
    uint64_t obj = cur + 8ULL;
    uint64_t ws_plus_1 = wz + 1ULL;
    uint64_t offset = ws_plus_1 * 8ULL;
    uint64_t next = cur + offset;
    uint64_t raw = hdr >> 8U & 3ULL;
    color_sem clr = raw == 0ULL ? White : raw == 1ULL ? Gray : raw == 2ULL ? Blue : Black;
    if (uu___is_Black(clr))
    {
      K___uint64_t_uint64_t res = flush_blue_impl(heap, cur_fb, cur_rw, cur_fv);
      uint64_t new_rw = fst__uint64_t_uint64_t(res);
      uint64_t new_fv = snd__uint64_t_uint64_t(res);
      uint64_t white_hdr = makeHeader(wz, White, getTag(hdr));
      write_word(heap, cur, white_hdr);
      current = next;
      fb_ref = 0ULL;
      rw_ref = new_rw;
      fp_ref = new_fv;
    }
    else
    {
      uint64_t new_fb = cur_rw == 0ULL ? obj : cur_fb;
      uint64_t new_rw = cur_rw + ws_plus_1;
      current = next;
      fb_ref = new_fb;
      rw_ref = new_rw;
    }
    uint64_t __anf0 = current;
    cond = __anf0 + 8ULL < heap_size_u640;
  }
  uint64_t final_fb = fb_ref;
  uint64_t final_rw = rw_ref;
  uint64_t final_fv = fp_ref;
  K___uint64_t_uint64_t res = flush_blue_impl(heap, final_fb, final_rw, final_fv);
  return snd__uint64_t_uint64_t(res);
}

uint64_t gen_alloc(gen_heap_t gh, uint64_t wosize, uint64_t tag)
{
  if (wosize <= max_young_wosize_u64)
  {
    uint64_t obj = minor_alloc(gh.minor, wosize, tag);
    if (obj == 0ULL)
    {
      uint64_t fp = *gh.fp_ref;
      K___uint64_t_uint64_t res = allocate(gh.major, fp, wosize);
      *gh.fp_ref = fst__uint64_t_uint64_t(res);
      return snd__uint64_t_uint64_t(res);
    }
    else
      return obj;
  }
  else
  {
    uint64_t fp = *gh.fp_ref;
    K___uint64_t_uint64_t res = allocate(gh.major, fp, wosize);
    *gh.fp_ref = fst__uint64_t_uint64_t(res);
    return snd__uint64_t_uint64_t(res);
  }
}

bool
minor_collect_full(
  gen_heap_t gh,
  uint64_t *roots,
  size_t nroots,
  uint64_t *fwd_arr,
  uint64_t *queue,
  uint64_t *slots,
  size_t nslots
)
{
  bool ok = cheney_promote_phase(gh.minor, gh.major, gh.fp_ref, fwd_arr, queue, roots, nroots);
  update_promoted_objects(gh.major, fwd_arr);
  rewrite_heap_slots(gh.major, fwd_arr, slots, nslots);
  rewrite_roots_impl(roots, fwd_arr, nroots);
  minor_heap_reset(gh.minor);
  return ok;
}

K___uint64_t_bool
gen_gc(
  gen_heap_t gh,
  uint64_t *roots,
  size_t nroots,
  uint64_t *fwd_arr,
  uint64_t *queue,
  uint64_t *slots,
  size_t nslots,
  gray_stack_rec st
)
{
  bool ok = minor_collect_full(gh, roots, nroots, fwd_arr, queue, slots, nslots);
  uint64_t fp_val = *gh.fp_ref;
  if (ok)
  {
    darken_roots_bounded(gh.major, st, roots, nroots);
    uint64_t final_fp = collect_with_roots(gh.major, st, fp_val);
    *gh.fp_ref = final_fp;
    return ((K___uint64_t_bool){ .fst = final_fp, .snd = ok });
  }
  else
    return ((K___uint64_t_bool){ .fst = fp_val, .snd = ok });
}

size_t minor_heap_size_sz;

static uint64_t make_header(uint64_t wosize, uint64_t tag)
{
  return wosize << 10U | tag;
}

uint64_t minor_read(minor_heap_t mh, uint64_t addr)
{
  size_t base = (size_t)addr;
  return read_u64_le(mh.data, base);
}

void minor_write(minor_heap_t mh, uint64_t addr, uint64_t v)
{
  size_t base = (size_t)addr;
  write_u64_le(mh.data, base, v);
}

uint64_t minor_alloc(minor_heap_t mh, uint64_t wosize, uint64_t tag)
{
  uint64_t bump = *mh.bump_ref;
  uint64_t obj_bytes = (wosize + 1ULL) * 8ULL;
  uint64_t new_bump = bump + obj_bytes;
  if (new_bump <= minor_heap_size_u64)
  {
    uint64_t hdr = make_header(wosize, tag);
    size_t base = (size_t)bump;
    write_u64_le(mh.data, base, hdr);
    *mh.bump_ref = new_bump;
    return bump + 8ULL;
  }
  else
    return 0ULL;
}

void minor_heap_reset(minor_heap_t mh)
{
  Pulse_Lib_Array_zeroize(minor_heap_size_sz, mh.data, (void *)0U);
  *mh.bump_ref = 0ULL;
}

minor_heap_t alloc_minor_heap(void)
{
  KRML_CHECK_SIZE(sizeof (uint8_t), minor_heap_size_sz);
  uint8_t data[minor_heap_size_sz];
  memset(data, 0U, minor_heap_size_sz * sizeof (uint8_t));
  uint64_t bump_ref = 0ULL;
  return ((minor_heap_t){ .data = data, .size = minor_heap_size_sz, .bump_ref = &bump_ref });
}

static void
translate_object_fields(
  minor_heap_t mh,
  uint64_t minor_base_addr,
  uint64_t bump,
  uint64_t obj_addr,
  uint64_t wosize
)
{
  uint64_t j = 0ULL;
  uint64_t __anf0 = j;
  bool cond = __anf0 < wosize;
  while (cond)
  {
    uint64_t jv = j;
    uint64_t field_addr = obj_addr + jv * 8ULL;
    uint64_t v = minor_read(mh, field_addr);
    if (v >= minor_base_addr)
    {
      uint64_t offset = v - minor_base_addr;
      if (offset < bump)
        if (v % 2ULL == 0ULL)
          minor_write(mh, field_addr, offset);
    }
    j = jv + 1ULL;
    uint64_t __anf0 = j;
    cond = __anf0 < wosize;
  }
}

void translate_minor_fields(minor_heap_t mh, uint64_t minor_base_addr)
{
  uint64_t bump = *mh.bump_ref;
  if (!(bump < 8ULL))
  {
    uint64_t pos = 0ULL;
    bool done_ = false;
    bool __anf0 = done_;
    bool cond = !__anf0;
    while (cond)
    {
      uint64_t pv = pos;
      uint64_t hdr = minor_read(mh, pv);
      uint64_t wz = hdr >> 10U;
      uint64_t tag_val = hdr & 0xFFULL;
      if (wz == 0ULL)
        done_ = true;
      else if (wz > bump / 8ULL)
        done_ = true;
      else
      {
        uint64_t obj_off = pv + 8ULL;
        uint64_t field_bytes = wz * 8ULL;
        uint64_t obj_end = obj_off + field_bytes;
        if (obj_end > bump)
          done_ = true;
        else
        {
          if (tag_val < 251ULL)
            translate_object_fields(mh, minor_base_addr, bump, obj_off, wz);
          uint64_t next = pv + (wz + 1ULL) * 8ULL;
          pos = next;
          if (next >= bump)
            done_ = true;
          else if (next > bump - 8ULL)
            done_ = true;
        }
      }
      bool __anf0 = done_;
      cond = !__anf0;
    }
  }
}

size_t fwd_arr_size_sz;

void synthesize_infix_forwarding(minor_heap_t mh, uint64_t *fwd_arr)
{
  uint64_t bump = *mh.bump_ref;
  if (!(bump < 8ULL))
  {
    uint64_t pos = 0ULL;
    bool done_ = false;
    bool __anf00 = done_;
    bool cond = !__anf00;
    while (cond)
    {
      uint64_t pv = pos;
      uint64_t hdr = minor_read(mh, pv);
      uint64_t wz = hdr >> 10U;
      uint64_t tag_val = hdr & 0xFFULL;
      if (wz == 0ULL)
        done_ = true;
      else if (wz > bump / 8ULL)
        done_ = true;
      else
      {
        uint64_t obj_off = pv + 8ULL;
        uint64_t field_bytes = wz * 8ULL;
        uint64_t obj_end = obj_off + field_bytes;
        if (obj_end > bump)
          done_ = true;
        else
        {
          if (tag_val == 247ULL)
          {
            uint64_t obj_off1 = pv + 8ULL;
            size_t parent_idx = (size_t)(obj_off1 / 8ULL);
            uint64_t parent_fwd = fwd_arr[parent_idx];
            if (parent_fwd > 0ULL)
              if (parent_fwd < 9223372036854775808ULL)
              {
                uint64_t obj_addr = pv + 8ULL;
                uint64_t j = 0ULL;
                uint64_t __anf0 = j;
                bool cond = __anf0 < wz;
                while (cond)
                {
                  uint64_t jv = j;
                  uint64_t field_off = obj_addr + jv * 8ULL;
                  uint64_t fhdr = minor_read(mh, field_off);
                  uint64_t ftag = fhdr & 0xFFULL;
                  if (ftag == 249ULL)
                  {
                    uint64_t infix_val_off = field_off + 8ULL;
                    uint64_t delta = infix_val_off - obj_addr;
                    uint64_t new_fwd = parent_fwd + delta;
                    size_t infix_idx = (size_t)(infix_val_off / 8ULL);
                    if (infix_idx < fwd_arr_size_sz)
                      fwd_arr[infix_idx] = new_fwd;
                  }
                  j = jv + 1ULL;
                  uint64_t __anf0 = j;
                  cond = __anf0 < wz;
                }
              }
          }
          uint64_t next = pv + (wz + 1ULL) * 8ULL;
          pos = next;
          if (next >= bump)
            done_ = true;
          else if (next > bump - 8ULL)
            done_ = true;
        }
      }
      bool __anf0 = done_;
      cond = !__anf0;
    }
  }
}

size_t find_infix_parents(minor_heap_t mh, uint64_t *roots, size_t nroots, size_t cap)
{
  uint64_t bump = *mh.bump_ref;
  if (bump < 8ULL)
    return (size_t)0U;
  else
  {
    uint64_t pos = 0ULL;
    bool done_ = false;
    size_t count = nroots;
    bool __anf00 = done_;
    bool cond = !__anf00;
    while (cond)
    {
      uint64_t pv = pos;
      uint64_t hdr = minor_read(mh, pv);
      uint64_t wz = hdr >> 10U;
      uint64_t tag_val = hdr & 0xFFULL;
      if (wz == 0ULL)
        done_ = true;
      else if (wz > bump / 8ULL)
        done_ = true;
      else
      {
        uint64_t obj_off = pv + 8ULL;
        uint64_t field_bytes = wz * 8ULL;
        uint64_t obj_end = obj_off + field_bytes;
        if (obj_end > bump)
          done_ = true;
        else
        {
          if (tag_val == 247ULL)
          {
            uint64_t obj_addr = pv + 8ULL;
            uint64_t j = 0ULL;
            uint64_t __anf0 = j;
            bool cond = __anf0 < wz;
            while (cond)
            {
              uint64_t jv = j;
              uint64_t field_off = obj_addr + jv * 8ULL;
              uint64_t fhdr = minor_read(mh, field_off);
              uint64_t ftag = fhdr & 0xFFULL;
              if (ftag == 249ULL)
              {
                size_t cnt_v = count;
                if (cnt_v < cap)
                {
                  roots[cnt_v] = obj_addr;
                  count = cnt_v + (size_t)1U;
                }
              }
              j = jv + 1ULL;
              uint64_t __anf0 = j;
              cond = __anf0 < wz;
            }
          }
          uint64_t next = pv + (wz + 1ULL) * 8ULL;
          pos = next;
          if (next >= bump)
            done_ = true;
          else if (next > bump - 8ULL)
            done_ = true;
        }
      }
      bool __anf0 = done_;
      cond = !__anf0;
    }
    size_t final_count = count;
    return final_count - nroots;
  }
}

size_t queue_size_sz;

void
forward_if_minor_infix(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref,
  uint64_t addr
)
{
  uint64_t hdr_addr0 = addr - 8ULL;
  uint64_t hdr = minor_read(minor, hdr_addr0);
  uint64_t wosize = hdr >> 10U;
  uint64_t parent = addr - wosize * 8ULL;
  size_t parent_idx = (size_t)(parent / 8ULL);
  uint64_t parent_fwd_val = fwd_arr[parent_idx];
  size_t idx = (size_t)(addr / 8ULL);
  if (!(parent_fwd_val == 0ULL))
  {
    uint64_t delta = addr - parent;
    if (!(parent_fwd_val >= heap_size_u640))
    {
      uint64_t sum = parent_fwd_val + delta;
      if (sum < heap_size_u640)
        fwd_arr[idx] = sum;
    }
  }
  else
  {
    uint64_t hdr_addr0 = parent - 8ULL;
    uint64_t hdr = minor_read(minor, hdr_addr0);
    uint64_t wosize1 = hdr >> 10U;
    uint64_t new_parent_addr;
    if (wosize1 == 0ULL)
      new_parent_addr = 0ULL;
    else
    {
      uint64_t fp = *fp_ref;
      K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize1);
      uint64_t new_fp = fst__uint64_t_uint64_t(res);
      uint64_t new_obj = snd__uint64_t_uint64_t(res);
      *fp_ref = new_fp;
      if (new_obj == 0ULL)
        new_parent_addr = 0ULL;
      else
      {
        copy_fields_loop(minor, major, parent, new_obj, wosize1);
        uint64_t hdr_addr = new_obj - 8ULL;
        uint64_t hdr = read_word(major, hdr_addr);
        uint64_t actual_wz = getWosize(hdr);
        if (actual_wz > wosize1)
        {
          uint64_t pad_addr = new_obj + wosize1 * 8ULL;
          write_word(major, pad_addr, 0ULL);
        }
        uint64_t minor_hdr = minor_read(minor, parent - 8ULL);
        uint64_t tag = getTag(minor_hdr);
        uint64_t major_hdr_addr = new_obj - 8ULL;
        uint64_t major_hdr = read_word(major, major_hdr_addr);
        uint64_t wz_read = getWosize(major_hdr);
        uint64_t new_hdr = makeHeader(wz_read, White, tag);
        write_word(major, major_hdr_addr, new_hdr);
        new_parent_addr = new_obj;
      }
    }
    if (new_parent_addr == 0ULL)
      *oom_ref = true;
    else
    {
      fwd_arr[parent_idx] = new_parent_addr;
      size_t bk = *back;
      if (bk < queue_size_sz)
      {
        queue[bk] = parent;
        *back = bk + (size_t)1U;
        uint64_t delta = addr - parent;
        uint64_t sum = new_parent_addr + delta;
        if (sum < heap_size_u640)
          fwd_arr[idx] = sum;
      }
    }
  }
}

void
forward_if_minor(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref,
  uint64_t addr
)
{
  if (!(addr < 8ULL))
    if (!(addr >= minor_heap_size_u64))
      if (!!(addr % 8ULL == 0ULL))
      {
        size_t idx = (size_t)(addr / 8ULL);
        uint64_t fwd_val = fwd_arr[idx];
        if (!!(fwd_val == 0ULL))
        {
          uint64_t hdr_addr0 = addr - 8ULL;
          uint64_t hdr = minor_read(minor, hdr_addr0);
          uint64_t tag = hdr & 0xFFULL;
          if (tag == 249ULL)
          {
            uint64_t hdr_addr0 = addr - 8ULL;
            uint64_t hdr = minor_read(minor, hdr_addr0);
            uint64_t wosize = hdr >> 10U;
            uint64_t parent = addr - wosize * 8ULL;
            size_t parent_idx = (size_t)(parent / 8ULL);
            uint64_t parent_fwd_val = fwd_arr[parent_idx];
            size_t idx1 = (size_t)(addr / 8ULL);
            if (!(parent_fwd_val == 0ULL))
            {
              uint64_t delta = addr - parent;
              if (!(parent_fwd_val >= heap_size_u640))
              {
                uint64_t sum = parent_fwd_val + delta;
                if (sum < heap_size_u640)
                  fwd_arr[idx1] = sum;
              }
            }
            else
            {
              uint64_t hdr_addr0 = parent - 8ULL;
              uint64_t hdr = minor_read(minor, hdr_addr0);
              uint64_t wosize1 = hdr >> 10U;
              uint64_t new_parent_addr;
              if (wosize1 == 0ULL)
                new_parent_addr = 0ULL;
              else
              {
                uint64_t fp = *fp_ref;
                K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize1);
                uint64_t new_fp = fst__uint64_t_uint64_t(res);
                uint64_t new_obj = snd__uint64_t_uint64_t(res);
                *fp_ref = new_fp;
                if (new_obj == 0ULL)
                  new_parent_addr = 0ULL;
                else
                {
                  copy_fields_loop(minor, major, parent, new_obj, wosize1);
                  uint64_t hdr_addr = new_obj - 8ULL;
                  uint64_t hdr = read_word(major, hdr_addr);
                  uint64_t actual_wz = getWosize(hdr);
                  if (actual_wz > wosize1)
                  {
                    uint64_t pad_addr = new_obj + wosize1 * 8ULL;
                    write_word(major, pad_addr, 0ULL);
                  }
                  uint64_t minor_hdr = minor_read(minor, parent - 8ULL);
                  uint64_t tag1 = getTag(minor_hdr);
                  uint64_t major_hdr_addr = new_obj - 8ULL;
                  uint64_t major_hdr = read_word(major, major_hdr_addr);
                  uint64_t wz_read = getWosize(major_hdr);
                  uint64_t new_hdr = makeHeader(wz_read, White, tag1);
                  write_word(major, major_hdr_addr, new_hdr);
                  new_parent_addr = new_obj;
                }
              }
              if (new_parent_addr == 0ULL)
                *oom_ref = true;
              else
              {
                fwd_arr[parent_idx] = new_parent_addr;
                size_t bk = *back;
                if (bk < queue_size_sz)
                {
                  queue[bk] = parent;
                  *back = bk + (size_t)1U;
                  uint64_t delta = addr - parent;
                  uint64_t sum = new_parent_addr + delta;
                  if (sum < heap_size_u640)
                    fwd_arr[idx1] = sum;
                }
              }
            }
          }
          else
          {
            uint64_t hdr_addr0 = addr - 8ULL;
            uint64_t hdr = minor_read(minor, hdr_addr0);
            uint64_t wosize = hdr >> 10U;
            if (!(wosize >= minor_heap_size_u64))
              if (!(addr + wosize * 8ULL > minor_heap_size_u64))
              {
                uint64_t hdr_addr0 = addr - 8ULL;
                uint64_t hdr = minor_read(minor, hdr_addr0);
                uint64_t wosize1 = hdr >> 10U;
                uint64_t new_addr;
                if (wosize1 == 0ULL)
                  new_addr = 0ULL;
                else
                {
                  uint64_t fp = *fp_ref;
                  K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize1);
                  uint64_t new_fp = fst__uint64_t_uint64_t(res);
                  uint64_t new_obj = snd__uint64_t_uint64_t(res);
                  *fp_ref = new_fp;
                  if (new_obj == 0ULL)
                    new_addr = 0ULL;
                  else
                  {
                    copy_fields_loop(minor, major, addr, new_obj, wosize1);
                    uint64_t hdr_addr = new_obj - 8ULL;
                    uint64_t hdr = read_word(major, hdr_addr);
                    uint64_t actual_wz = getWosize(hdr);
                    if (actual_wz > wosize1)
                    {
                      uint64_t pad_addr = new_obj + wosize1 * 8ULL;
                      write_word(major, pad_addr, 0ULL);
                    }
                    uint64_t minor_hdr = minor_read(minor, addr - 8ULL);
                    uint64_t tag1 = getTag(minor_hdr);
                    uint64_t major_hdr_addr = new_obj - 8ULL;
                    uint64_t major_hdr = read_word(major, major_hdr_addr);
                    uint64_t wz_read = getWosize(major_hdr);
                    uint64_t new_hdr = makeHeader(wz_read, White, tag1);
                    write_word(major, major_hdr_addr, new_hdr);
                    new_addr = new_obj;
                  }
                }
                if (new_addr == 0ULL)
                {
                  if (!(wosize == 0ULL))
                    *oom_ref = true;
                }
                else
                {
                  fwd_arr[idx] = new_addr;
                  size_t bk = *back;
                  if (bk < queue_size_sz)
                  {
                    queue[bk] = addr;
                    *back = bk + (size_t)1U;
                  }
                }
              }
          }
        }
      }
}

void
forward_roots(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref,
  uint64_t *roots,
  size_t nroots
)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < nroots;
  while (cond)
  {
    size_t iv = i;
    uint64_t r = roots[iv];
    if (!(r < 8ULL))
      if (!(r >= minor_heap_size_u64))
        if (!!(r % 8ULL == 0ULL))
        {
          size_t idx = (size_t)(r / 8ULL);
          uint64_t fwd_val = fwd_arr[idx];
          if (!!(fwd_val == 0ULL))
          {
            uint64_t hdr_addr0 = r - 8ULL;
            uint64_t hdr = minor_read(minor, hdr_addr0);
            uint64_t tag = hdr & 0xFFULL;
            if (tag == 249ULL)
            {
              uint64_t hdr_addr0 = r - 8ULL;
              uint64_t hdr = minor_read(minor, hdr_addr0);
              uint64_t wosize = hdr >> 10U;
              uint64_t parent = r - wosize * 8ULL;
              size_t parent_idx = (size_t)(parent / 8ULL);
              uint64_t parent_fwd_val = fwd_arr[parent_idx];
              size_t idx1 = (size_t)(r / 8ULL);
              if (!(parent_fwd_val == 0ULL))
              {
                uint64_t delta = r - parent;
                if (!(parent_fwd_val >= heap_size_u640))
                {
                  uint64_t sum = parent_fwd_val + delta;
                  if (sum < heap_size_u640)
                    fwd_arr[idx1] = sum;
                }
              }
              else
              {
                uint64_t hdr_addr0 = parent - 8ULL;
                uint64_t hdr = minor_read(minor, hdr_addr0);
                uint64_t wosize1 = hdr >> 10U;
                uint64_t new_parent_addr;
                if (wosize1 == 0ULL)
                  new_parent_addr = 0ULL;
                else
                {
                  uint64_t fp = *fp_ref;
                  K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize1);
                  uint64_t new_fp = fst__uint64_t_uint64_t(res);
                  uint64_t new_obj = snd__uint64_t_uint64_t(res);
                  *fp_ref = new_fp;
                  if (new_obj == 0ULL)
                    new_parent_addr = 0ULL;
                  else
                  {
                    copy_fields_loop(minor, major, parent, new_obj, wosize1);
                    uint64_t hdr_addr = new_obj - 8ULL;
                    uint64_t hdr = read_word(major, hdr_addr);
                    uint64_t actual_wz = getWosize(hdr);
                    if (actual_wz > wosize1)
                    {
                      uint64_t pad_addr = new_obj + wosize1 * 8ULL;
                      write_word(major, pad_addr, 0ULL);
                    }
                    uint64_t minor_hdr = minor_read(minor, parent - 8ULL);
                    uint64_t tag1 = getTag(minor_hdr);
                    uint64_t major_hdr_addr = new_obj - 8ULL;
                    uint64_t major_hdr = read_word(major, major_hdr_addr);
                    uint64_t wz_read = getWosize(major_hdr);
                    uint64_t new_hdr = makeHeader(wz_read, White, tag1);
                    write_word(major, major_hdr_addr, new_hdr);
                    new_parent_addr = new_obj;
                  }
                }
                if (new_parent_addr == 0ULL)
                  *oom_ref = true;
                else
                {
                  fwd_arr[parent_idx] = new_parent_addr;
                  size_t bk = *back;
                  if (bk < queue_size_sz)
                  {
                    queue[bk] = parent;
                    *back = bk + (size_t)1U;
                    uint64_t delta = r - parent;
                    uint64_t sum = new_parent_addr + delta;
                    if (sum < heap_size_u640)
                      fwd_arr[idx1] = sum;
                  }
                }
              }
            }
            else
            {
              uint64_t hdr_addr0 = r - 8ULL;
              uint64_t hdr = minor_read(minor, hdr_addr0);
              uint64_t wosize = hdr >> 10U;
              if (!(wosize >= minor_heap_size_u64))
                if (!(r + wosize * 8ULL > minor_heap_size_u64))
                {
                  uint64_t hdr_addr0 = r - 8ULL;
                  uint64_t hdr = minor_read(minor, hdr_addr0);
                  uint64_t wosize1 = hdr >> 10U;
                  uint64_t new_addr;
                  if (wosize1 == 0ULL)
                    new_addr = 0ULL;
                  else
                  {
                    uint64_t fp = *fp_ref;
                    K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize1);
                    uint64_t new_fp = fst__uint64_t_uint64_t(res);
                    uint64_t new_obj = snd__uint64_t_uint64_t(res);
                    *fp_ref = new_fp;
                    if (new_obj == 0ULL)
                      new_addr = 0ULL;
                    else
                    {
                      copy_fields_loop(minor, major, r, new_obj, wosize1);
                      uint64_t hdr_addr = new_obj - 8ULL;
                      uint64_t hdr = read_word(major, hdr_addr);
                      uint64_t actual_wz = getWosize(hdr);
                      if (actual_wz > wosize1)
                      {
                        uint64_t pad_addr = new_obj + wosize1 * 8ULL;
                        write_word(major, pad_addr, 0ULL);
                      }
                      uint64_t minor_hdr = minor_read(minor, r - 8ULL);
                      uint64_t tag1 = getTag(minor_hdr);
                      uint64_t major_hdr_addr = new_obj - 8ULL;
                      uint64_t major_hdr = read_word(major, major_hdr_addr);
                      uint64_t wz_read = getWosize(major_hdr);
                      uint64_t new_hdr = makeHeader(wz_read, White, tag1);
                      write_word(major, major_hdr_addr, new_hdr);
                      new_addr = new_obj;
                    }
                  }
                  if (new_addr == 0ULL)
                  {
                    if (!(wosize == 0ULL))
                      *oom_ref = true;
                  }
                  else
                  {
                    fwd_arr[idx] = new_addr;
                    size_t bk = *back;
                    if (bk < queue_size_sz)
                    {
                      queue[bk] = r;
                      *back = bk + (size_t)1U;
                    }
                  }
                }
            }
          }
        }
    i = iv + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < nroots;
  }
}

void
scan_loop(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref
)
{
  size_t scan = (size_t)0U;
  size_t s0 = scan;
  size_t b0 = *back;
  bool cond = s0 < b0;
  while (cond)
  {
    size_t s = scan;
    uint64_t obj = queue[s];
    if (obj < 8ULL)
      scan = s + (size_t)1U;
    else if (obj >= minor_heap_size_u64)
      scan = s + (size_t)1U;
    else if (!(obj % 8ULL == 0ULL))
      scan = s + (size_t)1U;
    else
    {
      uint64_t hdr_addr0 = obj - 8ULL;
      uint64_t hdr = minor_read(minor, hdr_addr0);
      uint64_t tag = hdr & 0xFFULL;
      uint64_t wosize;
      if (tag >= 251ULL)
        wosize = 0ULL;
      else
      {
        uint64_t hdr_addr = obj - 8ULL;
        uint64_t hdr = minor_read(minor, hdr_addr);
        wosize = hdr >> 10U;
      }
      if (wosize >= minor_heap_size_u64)
        scan = s + (size_t)1U;
      else if (obj + wosize * 8ULL > minor_heap_size_u64)
        scan = s + (size_t)1U;
      else
      {
        uint64_t field_idx = 0ULL;
        uint64_t __anf0 = field_idx;
        bool cond = __anf0 < wosize;
        while (cond)
        {
          uint64_t fi = field_idx;
          uint64_t field_addr = obj + fi * 8ULL;
          uint64_t child_raw = minor_read(minor, field_addr);
          uint64_t off = child_raw - minor_base_addr;
          uint64_t child = off < minor_heap_size_u64 && child_raw % 8ULL == 0ULL ? off : child_raw;
          if (!(child < 8ULL))
            if (!(child >= minor_heap_size_u64))
              if (!!(child % 8ULL == 0ULL))
              {
                size_t idx = (size_t)(child / 8ULL);
                uint64_t fwd_val = fwd_arr[idx];
                if (!!(fwd_val == 0ULL))
                {
                  uint64_t hdr_addr0 = child - 8ULL;
                  uint64_t hdr = minor_read(minor, hdr_addr0);
                  uint64_t tag = hdr & 0xFFULL;
                  if (tag == 249ULL)
                  {
                    uint64_t hdr_addr0 = child - 8ULL;
                    uint64_t hdr = minor_read(minor, hdr_addr0);
                    uint64_t wosize1 = hdr >> 10U;
                    uint64_t parent = child - wosize1 * 8ULL;
                    size_t parent_idx = (size_t)(parent / 8ULL);
                    uint64_t parent_fwd_val = fwd_arr[parent_idx];
                    size_t idx1 = (size_t)(child / 8ULL);
                    if (!(parent_fwd_val == 0ULL))
                    {
                      uint64_t delta = child - parent;
                      if (!(parent_fwd_val >= heap_size_u640))
                      {
                        uint64_t sum = parent_fwd_val + delta;
                        if (sum < heap_size_u640)
                          fwd_arr[idx1] = sum;
                      }
                    }
                    else
                    {
                      uint64_t hdr_addr0 = parent - 8ULL;
                      uint64_t hdr = minor_read(minor, hdr_addr0);
                      uint64_t wosize2 = hdr >> 10U;
                      uint64_t new_parent_addr;
                      if (wosize2 == 0ULL)
                        new_parent_addr = 0ULL;
                      else
                      {
                        uint64_t fp = *fp_ref;
                        K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize2);
                        uint64_t new_fp = fst__uint64_t_uint64_t(res);
                        uint64_t new_obj = snd__uint64_t_uint64_t(res);
                        *fp_ref = new_fp;
                        if (new_obj == 0ULL)
                          new_parent_addr = 0ULL;
                        else
                        {
                          copy_fields_loop(minor, major, parent, new_obj, wosize2);
                          uint64_t hdr_addr = new_obj - 8ULL;
                          uint64_t hdr = read_word(major, hdr_addr);
                          uint64_t actual_wz = getWosize(hdr);
                          if (actual_wz > wosize2)
                          {
                            uint64_t pad_addr = new_obj + wosize2 * 8ULL;
                            write_word(major, pad_addr, 0ULL);
                          }
                          uint64_t minor_hdr = minor_read(minor, parent - 8ULL);
                          uint64_t tag1 = getTag(minor_hdr);
                          uint64_t major_hdr_addr = new_obj - 8ULL;
                          uint64_t major_hdr = read_word(major, major_hdr_addr);
                          uint64_t wz_read = getWosize(major_hdr);
                          uint64_t new_hdr = makeHeader(wz_read, White, tag1);
                          write_word(major, major_hdr_addr, new_hdr);
                          new_parent_addr = new_obj;
                        }
                      }
                      if (new_parent_addr == 0ULL)
                        *oom_ref = true;
                      else
                      {
                        fwd_arr[parent_idx] = new_parent_addr;
                        size_t bk = *back;
                        if (bk < queue_size_sz)
                        {
                          queue[bk] = parent;
                          *back = bk + (size_t)1U;
                          uint64_t delta = child - parent;
                          uint64_t sum = new_parent_addr + delta;
                          if (sum < heap_size_u640)
                            fwd_arr[idx1] = sum;
                        }
                      }
                    }
                  }
                  else
                  {
                    uint64_t hdr_addr0 = child - 8ULL;
                    uint64_t hdr = minor_read(minor, hdr_addr0);
                    uint64_t wosize1 = hdr >> 10U;
                    if (!(wosize1 >= minor_heap_size_u64))
                      if (!(child + wosize1 * 8ULL > minor_heap_size_u64))
                      {
                        uint64_t hdr_addr0 = child - 8ULL;
                        uint64_t hdr = minor_read(minor, hdr_addr0);
                        uint64_t wosize2 = hdr >> 10U;
                        uint64_t new_addr;
                        if (wosize2 == 0ULL)
                          new_addr = 0ULL;
                        else
                        {
                          uint64_t fp = *fp_ref;
                          K___uint64_t_uint64_t res = allocate_part1(major, fp, wosize2);
                          uint64_t new_fp = fst__uint64_t_uint64_t(res);
                          uint64_t new_obj = snd__uint64_t_uint64_t(res);
                          *fp_ref = new_fp;
                          if (new_obj == 0ULL)
                            new_addr = 0ULL;
                          else
                          {
                            copy_fields_loop(minor, major, child, new_obj, wosize2);
                            uint64_t hdr_addr = new_obj - 8ULL;
                            uint64_t hdr = read_word(major, hdr_addr);
                            uint64_t actual_wz = getWosize(hdr);
                            if (actual_wz > wosize2)
                            {
                              uint64_t pad_addr = new_obj + wosize2 * 8ULL;
                              write_word(major, pad_addr, 0ULL);
                            }
                            uint64_t minor_hdr = minor_read(minor, child - 8ULL);
                            uint64_t tag1 = getTag(minor_hdr);
                            uint64_t major_hdr_addr = new_obj - 8ULL;
                            uint64_t major_hdr = read_word(major, major_hdr_addr);
                            uint64_t wz_read = getWosize(major_hdr);
                            uint64_t new_hdr = makeHeader(wz_read, White, tag1);
                            write_word(major, major_hdr_addr, new_hdr);
                            new_addr = new_obj;
                          }
                        }
                        if (new_addr == 0ULL)
                        {
                          if (!(wosize1 == 0ULL))
                            *oom_ref = true;
                        }
                        else
                        {
                          fwd_arr[idx] = new_addr;
                          size_t bk = *back;
                          if (bk < queue_size_sz)
                          {
                            queue[bk] = child;
                            *back = bk + (size_t)1U;
                          }
                        }
                      }
                  }
                }
              }
          field_idx = fi + 1ULL;
          uint64_t __anf0 = field_idx;
          cond = __anf0 < wosize;
        }
        scan = s + (size_t)1U;
      }
    }
    size_t s0 = scan;
    size_t b = *back;
    cond = s0 < b;
  }
}

bool
cheney_promote_phase(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  uint64_t *roots,
  size_t nroots
)
{
  Pulse_Lib_Array_fill(queue_size_sz, queue, 0ULL, (void *)0U);
  size_t back = (size_t)0U;
  bool oom = false;
  forward_roots(minor, major, fp_ref, fwd_arr, queue, &back, &oom, roots, nroots);
  scan_loop(minor, major, fp_ref, fwd_arr, queue, &back, &oom);
  bool oom_val = oom;
  return !oom_val;
}

void rewrite_roots_impl(uint64_t *roots, uint64_t *fwd_arr, size_t n)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t iv = i;
    uint64_t r = roots[iv];
    if (r >= 8ULL)
      if (r < minor_heap_size_u64)
        if (r % 8ULL == 0ULL)
        {
          size_t idx = (size_t)(r / 8ULL);
          uint64_t fwd_val = fwd_arr[idx];
          if (fwd_val == 0ULL)
            roots[iv] = r;
          else
            roots[iv] = fwd_val;
        }
        else
          roots[iv] = r;
      else
        roots[iv] = r;
    else
      roots[iv] = r;
    i = iv + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
}

void update_one_object(heap_t major, uint64_t *fwd_arr, uint64_t obj, uint64_t wosize)
{
  uint64_t i = 0ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 < wosize;
  while (cond)
  {
    uint64_t iv = i;
    uint64_t field_addr_u64 = obj + iv * 8ULL;
    uint64_t field_val_raw = read_word(major, field_addr_u64);
    uint64_t off = field_val_raw - minor_base_addr;
    uint64_t
    field_val = off < minor_heap_size_u64 && field_val_raw % 8ULL == 0ULL ? off : field_val_raw;
    if (field_val >= 8ULL)
      if (field_val < minor_heap_size_u64)
        if (field_val % 8ULL == 0ULL)
        {
          size_t idx = (size_t)(field_val / 8ULL);
          uint64_t fwd_val = fwd_arr[idx];
          if (!(fwd_val == 0ULL))
            write_word(major, field_addr_u64, fwd_val);
        }
    i = iv + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 < wosize;
  }
}

void update_all_objects(heap_t major, uint64_t *fwd_arr)
{
  uint64_t pos = zero_addr1;
  bool done = false;
  bool __anf00 = done;
  bool cond = !__anf00;
  while (cond)
  {
    uint64_t p = pos;
    uint64_t hdr = read_word(major, p);
    uint64_t wosize = hdr >> 10U;
    uint64_t obj = p + 8ULL;
    uint64_t raw_color = hdr >> 8U & 3ULL;
    if (raw_color == 2ULL)
    {
      uint64_t total_words = wosize + 1ULL;
      uint64_t total_bytes = total_words * 8ULL;
      uint64_t next_pos = p + total_bytes;
      pos = next_pos;
      done = next_pos + 8ULL >= heap_size_u640;
    }
    else
    {
      uint64_t tag = getTag(hdr);
      if (tag >= no_scan_tag)
      {
        uint64_t total_words = wosize + 1ULL;
        uint64_t total_bytes = total_words * 8ULL;
        uint64_t next_pos = p + total_bytes;
        pos = next_pos;
        done = next_pos + 8ULL >= heap_size_u640;
      }
      else
      {
        uint64_t total_words = wosize + 1ULL;
        uint64_t total_bytes = total_words * 8ULL;
        uint64_t next_pos = p + total_bytes;
        uint64_t i = 0ULL;
        uint64_t __anf0 = i;
        bool cond = __anf0 < wosize;
        while (cond)
        {
          uint64_t iv = i;
          uint64_t field_addr_u64 = obj + iv * 8ULL;
          uint64_t field_val_raw = read_word(major, field_addr_u64);
          uint64_t off = field_val_raw - minor_base_addr;
          uint64_t
          field_val =
            off < minor_heap_size_u64 && field_val_raw % 8ULL == 0ULL ? off
                                                                      : field_val_raw;
          if (field_val >= 8ULL)
            if (field_val < minor_heap_size_u64)
              if (field_val % 8ULL == 0ULL)
              {
                size_t idx = (size_t)(field_val / 8ULL);
                uint64_t fwd_val = fwd_arr[idx];
                if (!(fwd_val == 0ULL))
                  write_word(major, field_addr_u64, fwd_val);
              }
          i = iv + 1ULL;
          uint64_t __anf0 = i;
          cond = __anf0 < wosize;
        }
        pos = next_pos;
        done = next_pos + 8ULL >= heap_size_u640;
      }
    }
    bool __anf0 = done;
    cond = !__anf0;
  }
}

void rewrite_heap_slots(heap_t major, uint64_t *fwd_arr, uint64_t *slots, size_t n)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < n;
  while (cond)
  {
    size_t iv = i;
    uint64_t slot_addr = slots[iv];
    uint64_t field_val_raw = read_word(major, slot_addr);
    uint64_t off = field_val_raw - minor_base_addr;
    uint64_t
    field_val = off < minor_heap_size_u64 && field_val_raw % 8ULL == 0ULL ? off : field_val_raw;
    if (field_val >= 8ULL)
      if (field_val < minor_heap_size_u64)
        if (field_val % 8ULL == 0ULL)
        {
          size_t idx = (size_t)(field_val / 8ULL);
          uint64_t fwd_val = fwd_arr[idx];
          if (!(fwd_val == 0ULL))
            write_word(major, slot_addr, fwd_val);
        }
    i = iv + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < n;
  }
}

void update_promoted_objects(heap_t major, uint64_t *fwd_arr)
{
  size_t fwd_size = (size_t)(minor_heap_size_u64 / 8ULL);
  size_t i = (size_t)0U;
  size_t __anf00 = i;
  bool cond = __anf00 < fwd_size;
  while (cond)
  {
    size_t iv = i;
    uint64_t major_addr = fwd_arr[iv];
    if (major_addr == 0ULL)
      i = iv + (size_t)1U;
    else
    {
      uint64_t hdr_pos = major_addr - 8ULL;
      uint64_t hdr = read_word(major, hdr_pos);
      uint64_t wosize = hdr >> 10U;
      uint64_t tag = hdr & 0xFFULL;
      if (wosize > 0ULL)
      {
        bool is_scannable = tag < 251ULL && !(tag == 249ULL);
        if (is_scannable)
        {
          uint64_t body_end = major_addr + wosize * 8ULL;
          if (body_end <= heap_size_u640)
          {
            uint64_t i1 = 0ULL;
            uint64_t __anf0 = i1;
            bool cond = __anf0 < wosize;
            while (cond)
            {
              uint64_t iv1 = i1;
              uint64_t field_addr_u64 = major_addr + iv1 * 8ULL;
              uint64_t field_val_raw = read_word(major, field_addr_u64);
              uint64_t off = field_val_raw - minor_base_addr;
              uint64_t
              field_val =
                off < minor_heap_size_u64 && field_val_raw % 8ULL == 0ULL ? off
                                                                          : field_val_raw;
              if (field_val >= 8ULL)
                if (field_val < minor_heap_size_u64)
                  if (field_val % 8ULL == 0ULL)
                  {
                    size_t idx = (size_t)(field_val / 8ULL);
                    uint64_t fwd_val = fwd_arr[idx];
                    if (!(fwd_val == 0ULL))
                      write_word(major, field_addr_u64, fwd_val);
                  }
              i1 = iv1 + 1ULL;
              uint64_t __anf0 = i1;
              cond = __anf0 < wosize;
            }
            i = iv + (size_t)1U;
          }
          else
            i = iv + (size_t)1U;
        }
        else
          i = iv + (size_t)1U;
      }
      else
        i = iv + (size_t)1U;
    }
    size_t __anf0 = i;
    cond = __anf0 < fwd_size;
  }
}

uint64_t collect_with_roots(heap_t heap, gray_stack_rec st, uint64_t fp)
{
  KRML_MAYBE_UNUSED_VAR(fp);
  mark_loop_bounded(heap, st);
  return fused_sweep_coalesce(heap);
}

uint64_t collect(heap_t heap, gray_stack_rec st, uint64_t fp)
{
  return collect_with_roots(heap, st, fp);
}

static bool is_valid_fp(uint64_t v)
{
  return v >= zero_addr1 + 8ULL && v < heap_size_u640 && v % 8ULL == 0ULL;
}

uint64_t init_heap(heap_t heap)
{
  uint64_t total_words = heap_size_u640 / 8ULL;
  if (total_words < 2ULL)
    return 0ULL;
  else
  {
    uint64_t wz = total_words - 1ULL;
    uint64_t hdr = makeHeader(wz, blue, 0ULL);
    write_word(heap, zero_addr1, hdr);
    write_word(heap, 8ULL, 0ULL);
    return 8ULL;
  }
}

K___uint64_t_uint64_t allocate(heap_t heap, uint64_t fp, uint64_t wosize)
{
  uint64_t wz = wosize == 0ULL ? 1ULL : wosize;
  uint64_t head_fp = fp;
  uint64_t prev_fp = 0ULL;
  uint64_t cur_fp = fp;
  uint64_t result_obj = 0ULL;
  bool go = true;
  uint64_t fuel_ref = heap_size_u640 / 8ULL;
  while (go)
  {
    uint64_t vfuel = fuel_ref;
    if (vfuel == 0ULL)
      go = false;
    else
    {
      uint64_t vcur = cur_fp;
      bool valid = is_valid_fp(vcur);
      if (!valid)
        go = false;
      else
      {
        uint64_t hd_addr = hd_address(vcur);
        uint64_t hdr = read_word(heap, hd_addr);
        uint64_t block_wz = getWosize0(hdr);
        uint64_t next = read_word(heap, vcur);
        if (block_wz >= wz)
        {
          uint64_t leftover = block_wz - wz;
          uint64_t vp = prev_fp;
          if (leftover >= 2ULL)
          {
            uint64_t wz_plus_1 = wz + 1ULL;
            uint64_t offset = wz_plus_1 * 8ULL;
            uint64_t rem_hd_off = hd_addr + offset;
            if (rem_hd_off >= heap_size_u640)
            {
              uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
              write_word(heap, hd_addr, alloc_hdr);
              if (vp == 0ULL)
              {
                head_fp = next;
                result_obj = vcur;
                go = false;
              }
              else
              {
                write_word(heap, vp, next);
                result_obj = vcur;
                go = false;
              }
            }
            else
            {
              uint64_t rem_obj = rem_hd_off + 8ULL;
              if (rem_obj >= heap_size_u640)
              {
                uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
                write_word(heap, hd_addr, alloc_hdr);
                uint64_t rem_wz_u = leftover - 1ULL;
                uint64_t rem_hdr = makeHeader(rem_wz_u, blue, 0ULL);
                write_word(heap, rem_hd_off, rem_hdr);
                if (vp == 0ULL)
                {
                  head_fp = rem_obj;
                  result_obj = vcur;
                  go = false;
                }
                else
                {
                  write_word(heap, vp, rem_obj);
                  result_obj = vcur;
                  go = false;
                }
              }
              else
              {
                uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
                write_word(heap, hd_addr, alloc_hdr);
                uint64_t rem_wz_u = leftover - 1ULL;
                uint64_t rem_hdr = makeHeader(rem_wz_u, blue, 0ULL);
                write_word(heap, rem_hd_off, rem_hdr);
                write_word(heap, rem_obj, next);
                if (vp == 0ULL)
                {
                  head_fp = rem_obj;
                  result_obj = vcur;
                  go = false;
                }
                else
                {
                  write_word(heap, vp, rem_obj);
                  result_obj = vcur;
                  go = false;
                }
              }
            }
          }
          else
          {
            uint64_t alloc_hdr = makeHeader(block_wz, white, 0ULL);
            write_word(heap, hd_addr, alloc_hdr);
            if (vp == 0ULL)
            {
              head_fp = next;
              result_obj = vcur;
              go = false;
            }
            else
            {
              write_word(heap, vp, next);
              result_obj = vcur;
              go = false;
            }
          }
        }
        else
        {
          prev_fp = vcur;
          cur_fp = next;
          fuel_ref = vfuel - 1ULL;
        }
      }
    }
  }
  uint64_t final_fp = head_fp;
  uint64_t final_obj = result_obj;
  return ((K___uint64_t_uint64_t){ .fst = final_fp, .snd = final_obj });
}

K___uint64_t_uint64_t allocate_part1(heap_t heap, uint64_t fp, uint64_t wosize)
{
  uint64_t wz = wosize == 0ULL ? 1ULL : wosize;
  uint64_t head_fp = fp;
  uint64_t prev_fp = 0ULL;
  uint64_t cur_fp = fp;
  uint64_t result_obj = 0ULL;
  bool go = true;
  uint64_t fuel_ref = heap_size_u640 / 8ULL;
  while (go)
  {
    uint64_t vfuel = fuel_ref;
    if (vfuel == 0ULL)
      go = false;
    else
    {
      uint64_t vcur = cur_fp;
      bool valid = is_valid_fp(vcur);
      if (!valid)
        go = false;
      else
      {
        uint64_t hd_addr = hd_address(vcur);
        uint64_t hdr = read_word(heap, hd_addr);
        uint64_t block_wz = getWosize0(hdr);
        uint64_t next = read_word(heap, vcur);
        if (block_wz >= wz)
        {
          uint64_t leftover = block_wz - wz;
          uint64_t vp = prev_fp;
          if (leftover >= 2ULL)
          {
            uint64_t wz_plus_1 = wz + 1ULL;
            uint64_t offset = wz_plus_1 * 8ULL;
            uint64_t rem_hd_off = hd_addr + offset;
            if (rem_hd_off >= heap_size_u640)
            {
              uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
              write_word(heap, hd_addr, alloc_hdr);
              if (vp == 0ULL)
              {
                head_fp = next;
                result_obj = vcur;
                go = false;
              }
              else
              {
                write_word(heap, vp, next);
                result_obj = vcur;
                go = false;
              }
            }
            else
            {
              uint64_t rem_obj = rem_hd_off + 8ULL;
              if (rem_obj >= heap_size_u640)
              {
                uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
                write_word(heap, hd_addr, alloc_hdr);
                uint64_t rem_wz_u = leftover - 1ULL;
                uint64_t rem_hdr = makeHeader(rem_wz_u, blue, 0ULL);
                write_word(heap, rem_hd_off, rem_hdr);
                if (vp == 0ULL)
                {
                  head_fp = rem_obj;
                  result_obj = vcur;
                  go = false;
                }
                else
                {
                  write_word(heap, vp, rem_obj);
                  result_obj = vcur;
                  go = false;
                }
              }
              else
              {
                uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
                write_word(heap, hd_addr, alloc_hdr);
                uint64_t rem_wz_u = leftover - 1ULL;
                uint64_t rem_hdr = makeHeader(rem_wz_u, blue, 0ULL);
                write_word(heap, rem_hd_off, rem_hdr);
                write_word(heap, rem_obj, next);
                if (vp == 0ULL)
                {
                  head_fp = rem_obj;
                  result_obj = vcur;
                  go = false;
                }
                else
                {
                  write_word(heap, vp, rem_obj);
                  result_obj = vcur;
                  go = false;
                }
              }
            }
          }
          else
          {
            uint64_t alloc_hdr = makeHeader(block_wz, white, 0ULL);
            write_word(heap, hd_addr, alloc_hdr);
            if (vp == 0ULL)
            {
              head_fp = next;
              result_obj = vcur;
              go = false;
            }
            else
            {
              write_word(heap, vp, next);
              result_obj = vcur;
              go = false;
            }
          }
        }
        else
        {
          prev_fp = vcur;
          cur_fp = next;
          fuel_ref = vfuel - 1ULL;
        }
      }
    }
  }
  uint64_t final_fp = head_fp;
  uint64_t final_obj = result_obj;
  return ((K___uint64_t_uint64_t){ .fst = final_fp, .snd = final_obj });
}

static void darken_write_gray(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t new_hdr = makeHeader(getWosize0(hdr), gray, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
}

void darken_if_white_bounded(heap_t heap, gray_stack_rec st, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t raw = hdr >> 8U & 3ULL;
  color_sem c = raw == 0ULL ? White : raw == 1ULL ? Gray : raw == 2ULL ? Blue : Black;
  uint64_t obj = f_address(h_addr);
  if (c == white)
  {
    darken_write_gray(heap, h_addr);
    bool full = is_full(st);
    if (!full)
      push(st, obj);
  }
}

void check_and_darken_bounded(heap_t heap, gray_stack_rec st, uint64_t v)
{
  bool is_ptr = is_pointer(v);
  if (is_ptr)
  {
    uint64_t target_hdr_raw = v - 8ULL;
    uint64_t target_hdr = target_hdr_raw;
    uint64_t hdr = read_word(heap, target_hdr);
    uint64_t t = getTag(hdr);
    uint64_t wz = getWosize0(hdr);
    uint64_t off = wz * 8ULL;
    if (t == infix_tag && v >= off + 8ULL)
    {
      uint64_t parent_hdr = v - off - 8ULL;
      darken_if_white_bounded(heap, st, parent_hdr);
    }
    else
      darken_if_white_bounded(heap, st, target_hdr);
  }
}

void darken_roots_bounded(heap_t heap, gray_stack_rec st, uint64_t *roots, size_t nroots)
{
  size_t i = (size_t)0U;
  size_t __anf0 = i;
  bool cond = __anf0 < nroots;
  while (cond)
  {
    size_t iv = i;
    uint64_t r = roots[iv];
    check_and_darken_bounded(heap, st, r);
    i = iv + (size_t)1U;
    size_t __anf0 = i;
    cond = __anf0 < nroots;
  }
}

static void
push_step_body_bounded(heap_t heap, gray_stack_rec st, uint64_t h_addr, uint64_t curr_i)
{
  uint64_t v = read_field(heap, h_addr, curr_i);
  check_and_darken_bounded(heap, st, v);
}

static void
push_children_bounded_impl(heap_t heap, gray_stack_rec st, uint64_t h_addr, uint64_t wz)
{
  uint64_t obj = f_address(h_addr);
  KRML_MAYBE_UNUSED_VAR(obj);
  uint64_t i = 1ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 <= wz;
  while (cond)
  {
    uint64_t curr_i = i;
    push_step_body_bounded(heap, st, h_addr, curr_i);
    i = curr_i + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 <= wz;
  }
}

static void mark_write_black(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t new_hdr = makeHeader(getWosize0(hdr), black, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
}

static K___uint64_t_uint64_t mark_read_header(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t wz = getWosize0(hdr);
  uint64_t tag = getTag(hdr);
  return ((K___uint64_t_uint64_t){ .fst = wz, .snd = tag });
}

static void mark_step_bounded_impl(heap_t heap, gray_stack_rec st)
{
  uint64_t f_addr = pop(st);
  uint64_t h_addr_raw = f_addr - 8ULL;
  uint64_t h_addr = h_addr_raw;
  K___uint64_t_uint64_t r = mark_read_header(heap, h_addr);
  uint64_t wz = fst__uint64_t_uint64_t(r);
  uint64_t tag = snd__uint64_t_uint64_t(r);
  mark_write_black(heap, h_addr);
  if (!(tag >= no_scan_tag))
    push_children_bounded_impl(heap, st, h_addr, wz);
}

static void mark_inner_loop_impl(heap_t heap, gray_stack_rec st)
{
  bool go = true;
  while (go)
  {
    bool empty = is_empty(st);
    if (empty)
      go = false;
    else
      mark_step_bounded_impl(heap, st);
  }
}

static bool is_gray_check(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t raw = hdr >> 8U & 3ULL;
  color_sem c = raw == 0ULL ? White : raw == 1ULL ? Gray : raw == 2ULL ? Blue : Black;
  uint64_t obj = f_address(h_addr);
  KRML_MAYBE_UNUSED_VAR(obj);
  return c == gray;
}

static void rescan_push_if_gray(heap_t heap, gray_stack_rec st, uint64_t h_addr)
{
  bool b = is_gray_check(heap, h_addr);
  if (b)
  {
    bool full = is_full(st);
    if (!full)
    {
      uint64_t obj = f_address(h_addr);
      push(st, obj);
    }
  }
}

static void rescan_heap_impl(heap_t heap, gray_stack_rec st)
{
  uint64_t heap_sz = heap_size_u640;
  uint64_t current = zero_addr0;
  uint64_t v0 = current;
  bool cond = v0 + 8ULL < heap_sz;
  while (cond)
  {
    uint64_t v = current;
    uint64_t hdr = read_word(heap, v);
    uint64_t wz = getWosize0(hdr);
    rescan_push_if_gray(heap, st, v);
    uint64_t skip = 1ULL + wz;
    uint64_t offset = skip * 8ULL;
    uint64_t next = v + offset;
    current = next;
    uint64_t v0 = current;
    cond = v0 + 8ULL < heap_sz;
  }
}

void mark_loop_bounded(heap_t heap, gray_stack_rec st)
{
  mark_inner_loop_impl(heap, st);
  bool go = true;
  while (go)
  {
    rescan_heap_impl(heap, st);
    bool empty = is_empty(st);
    if (empty)
      go = false;
    else
      mark_inner_loop_impl(heap, st);
  }
}

