/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/pulse-verified-gc/generational/../fstar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -bundle GC.Gen.Impl+GC.Gen.Impl.MinorHeap+GC.Gen.Impl.Cheney+GC.Gen.Impl.UpdatePtrs+GC.Impl+GC.Impl.Allocator+GC.Impl.MarkBounded=GC.Gen.Impl.*,GC.Impl.*[rename=GC_Gen_Impl] -bundle FStar.Pervasives.Native -bundle GC.Spec.ZeroAddr=GC.Spec.ZeroAddr -bundle GC.Gen.Base,GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Gen.Impl -no-prefix GC.Gen.Impl.MinorHeap -no-prefix GC.Gen.Impl.Cheney -no-prefix GC.Gen.Impl.Promote -no-prefix GC.Gen.Impl.UpdatePtrs -no-prefix GC.Gen.Base -no-prefix GC.Impl -no-prefix GC.Impl.Fields -no-prefix GC.Impl.MarkBounded -no-prefix GC.Impl.Coalesce -no-prefix GC.Impl.FusedSweepCoalesce -no-prefix GC.Impl.Allocator -no-prefix GC.Impl.ArrayWord -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -no-prefix GC.Spec.ZeroAddr -no-prefix GC.Spec.Base -no-prefix GC.Spec.Heap -no-prefix GC.Spec.Object -no-prefix GC.Lib.Header -no-prefix GC.Lib.Address -warn-error -2-9-15 _output/GC_Gen_Impl.krml _output/GC_Gen_Impl_MinorHeap.krml _output/GC_Gen_Impl_Cheney.krml _output/GC_Gen_Impl_Promote.krml _output/GC_Gen_Impl_UpdatePtrs.krml _output/GC_Gen_Base.krml _output/GC_Impl.krml _output/GC_Impl_Fields.krml _output/GC_Impl_MarkBounded.krml _output/GC_Impl_Coalesce.krml _output/GC_Impl_FusedSweepCoalesce.krml _output/GC_Impl_Allocator.krml _output/GC_Impl_ArrayWord.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/GC_Spec_ZeroAddr.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml _output/FStar_Pervasives_Native.krml
  F* version: <unknown>
  KaRaMeL version: 2309d841d896e5f2b0fec73884657eefea5fad6e
 */

#include "internal/GC_Gen_Base_GC_Spec_GC_Lib_Header_GC_Lib_Address.h"

uint64_t heap_size_u640;

uint64_t zero_addr0;

bool uu___is_Black(color_sem projectee)
{
  switch (projectee)
  {
    case Black:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

static uint32_t wosize_shift = 10U;

uint64_t getWosize(uint64_t header)
{
  return header >> wosize_shift;
}

uint64_t minor_heap_size_u64 = 2048ULL;

uint64_t max_young_wosize_u64 = 128ULL;

uint64_t minor_base_addr = 0ULL;

