/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/pulse-verified-gc/generational/../fstar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -bundle GC.Gen.Impl+GC.Gen.Impl.MinorHeap+GC.Gen.Impl.Cheney+GC.Gen.Impl.UpdatePtrs+GC.Impl+GC.Impl.Allocator+GC.Impl.MarkBounded=GC.Gen.Impl.*,GC.Impl.*[rename=GC_Gen_Impl] -bundle FStar.Pervasives.Native -bundle GC.Spec.ZeroAddr=GC.Spec.ZeroAddr -bundle GC.Gen.Base,GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Gen.Impl -no-prefix GC.Gen.Impl.MinorHeap -no-prefix GC.Gen.Impl.Cheney -no-prefix GC.Gen.Impl.Promote -no-prefix GC.Gen.Impl.UpdatePtrs -no-prefix GC.Gen.Base -no-prefix GC.Impl -no-prefix GC.Impl.Fields -no-prefix GC.Impl.MarkBounded -no-prefix GC.Impl.Coalesce -no-prefix GC.Impl.FusedSweepCoalesce -no-prefix GC.Impl.Allocator -no-prefix GC.Impl.ArrayWord -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -no-prefix GC.Spec.ZeroAddr -no-prefix GC.Spec.Base -no-prefix GC.Spec.Heap -no-prefix GC.Spec.Object -no-prefix GC.Lib.Header -no-prefix GC.Lib.Address -warn-error -2-9-15 _output/GC_Gen_Impl.krml _output/GC_Gen_Impl_MinorHeap.krml _output/GC_Gen_Impl_Cheney.krml _output/GC_Gen_Impl_Promote.krml _output/GC_Gen_Impl_UpdatePtrs.krml _output/GC_Gen_Base.krml _output/GC_Impl.krml _output/GC_Impl_Fields.krml _output/GC_Impl_MarkBounded.krml _output/GC_Impl_Coalesce.krml _output/GC_Impl_FusedSweepCoalesce.krml _output/GC_Impl_Allocator.krml _output/GC_Impl_ArrayWord.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/GC_Spec_ZeroAddr.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml _output/FStar_Pervasives_Native.krml
  F* version: <unknown>
  KaRaMeL version: 2309d841d896e5f2b0fec73884657eefea5fad6e
 */

#ifndef GC_Gen_Impl_H
#define GC_Gen_Impl_H

#include "krmllib.h"

typedef struct heap_t_s
{
  uint8_t *data;
  size_t size;
}
heap_t;

typedef struct gray_stack_rec_s
{
  uint64_t *storage;
  size_t *top;
  size_t cap;
}
gray_stack_rec;

typedef struct minor_heap_t_s
{
  uint8_t *data;
  size_t size;
  uint64_t *bump_ref;
}
minor_heap_t;

typedef struct K___uint64_t_uint64_t_s
{
  uint64_t fst;
  uint64_t snd;
}
K___uint64_t_uint64_t;

typedef struct gen_heap_t_s
{
  minor_heap_t minor;
  heap_t major;
  uint64_t *fp_ref;
}
gen_heap_t;

uint64_t gen_alloc(gen_heap_t gh, uint64_t wosize, uint64_t tag);

bool
minor_collect_full(
  gen_heap_t gh,
  uint64_t *roots,
  size_t nroots,
  uint64_t *fwd_arr,
  uint64_t *queue,
  uint64_t *slots,
  size_t nslots
);

typedef struct K___uint64_t_bool_s
{
  uint64_t fst;
  bool snd;
}
K___uint64_t_bool;

K___uint64_t_bool
gen_gc(
  gen_heap_t gh,
  uint64_t *roots,
  size_t nroots,
  uint64_t *fwd_arr,
  uint64_t *queue,
  uint64_t *slots,
  size_t nslots,
  gray_stack_rec st
);

uint64_t minor_read(minor_heap_t mh, uint64_t addr);

void minor_write(minor_heap_t mh, uint64_t addr, uint64_t v);

uint64_t minor_alloc(minor_heap_t mh, uint64_t wosize, uint64_t tag);

void minor_heap_reset(minor_heap_t mh);

minor_heap_t alloc_minor_heap(void);

void translate_minor_fields(minor_heap_t mh, uint64_t minor_base_addr);

void synthesize_infix_forwarding(minor_heap_t mh, uint64_t *fwd_arr);

size_t find_infix_parents(minor_heap_t mh, uint64_t *roots, size_t nroots, size_t cap);

extern size_t queue_size_sz;

void
forward_if_minor_infix(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref,
  uint64_t addr
);

void
forward_if_minor(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref,
  uint64_t addr
);

void
forward_roots(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref,
  uint64_t *roots,
  size_t nroots
);

void
scan_loop(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  size_t *back,
  bool *oom_ref
);

bool
cheney_promote_phase(
  minor_heap_t minor,
  heap_t major,
  uint64_t *fp_ref,
  uint64_t *fwd_arr,
  uint64_t *queue,
  uint64_t *roots,
  size_t nroots
);

void rewrite_roots_impl(uint64_t *roots, uint64_t *fwd_arr, size_t n);

void update_one_object(heap_t major, uint64_t *fwd_arr, uint64_t obj, uint64_t wosize);

void update_all_objects(heap_t major, uint64_t *fwd_arr);

void rewrite_heap_slots(heap_t major, uint64_t *fwd_arr, uint64_t *slots, size_t n);

void update_promoted_objects(heap_t major, uint64_t *fwd_arr);

uint64_t collect_with_roots(heap_t heap, gray_stack_rec st, uint64_t fp);

uint64_t collect(heap_t heap, gray_stack_rec st, uint64_t fp);

uint64_t init_heap(heap_t heap);

K___uint64_t_uint64_t allocate(heap_t heap, uint64_t fp, uint64_t wosize);

K___uint64_t_uint64_t allocate_part1(heap_t heap, uint64_t fp, uint64_t wosize);

void darken_if_white_bounded(heap_t heap, gray_stack_rec st, uint64_t h_addr);

void check_and_darken_bounded(heap_t heap, gray_stack_rec st, uint64_t v);

void darken_roots_bounded(heap_t heap, gray_stack_rec st, uint64_t *roots, size_t nroots);

void mark_loop_bounded(heap_t heap, gray_stack_rec st);


#define GC_Gen_Impl_H_DEFINED
#endif /* GC_Gen_Impl_H */
